name: Deploy .NET Azure Function App

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '6.0.x'
  AZURE_FUNCTIONAPP_NAME: MyHTTPTrigger
  AZURE_FUNCTIONAPP_PACKAGE_PATH: .

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout
      uses: actions/checkout@v4

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    # Restore dependencies
    - name: Restore
      run: dotnet restore FunctionApp1/FunctionApp1.csproj

    # Build
    - name: Build
      run: dotnet build FunctionApp1/FunctionApp1.csproj -c Release --no-restore

    # Publish Function App
    - name: Publish
      run: |
        dotnet publish FunctionApp1/FunctionApp1.csproj -c Release -o publish

        - name: Azure Login
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
    # Deploy to Azure Function App
    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME}}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ./publish




